
= mill-aspectj - AspectJ compiler support for mill
:version: SNAPSHOT
:aspectjVersion: 1.9.4
:toc:
:toc-placement: preamble

Documentation for mill-aspectj, a mill plugin to support the https://projects.eclipse.org/projects/tools.aspectj[AspectJ language and compiler].

== Quickstart

[source,scala,subs="attributes,verbatim"]
----
import mill._
import mill.scalalib._
import mill.define._

// Load the plugin from Maven Central via ivy/coursier
import $ivy.`de.tototec::de.tobiasroeser.mill.aspectj:{version}`, de.tobiasroeser.mill.aspectj._

object main extends AspectjModule {

  // Select the AspectJ version
  def aspectjVersion = T{ "{aspectjVersion}" }

  // Set AspectJ options, e.g. the language level and annotation processor
  // Run `mill main.ajcHelp` to get a list of supported options
  def ajcOptions = Seq("-8", "-proc:none")

}
----

== Configuration

Your module needs to extend `de.tobiasroeser.mill.aspectj.AspectjModule` which itself extends `mill.scalalib.JavaModule`.

The module trait `de.tobiasroeser.mill.aspectj.AspectjModule` has the following configuration options (over those from `mill.scalalib.JavaModule`).

* `def aspectjVersion: T[String]` - The AspectJ version. _Required_.
For a list of available releases refer to the https://www.eclipse.org/aspectj/downloads.php[AspectJ Download Page].

* `def ivyDeps: T[Agg[Dep]]` - The compile and runtime dependencies.
Contains by default the `aspectjrt.jar` which is resolved via ivy (`ivy"org.aspectj:aspectjrt:${aspectjVersion()}"`).
If you do do not use `super.ivyDeps()` when overriding this def, you need to provide the `aspectjrt.jar` manually.

* `def aspectjToolsDeps: T[Agg[Dep]]` - The ivy dependencies representing the aspectj compiler classes, which is typically a `aspectjtools.jar`.
Default to `ivy"org.aspectj:aspectjtools:${aspectjVersion()}"`.

* `def aspectjToolsClasspath: T[Agg[PathRef]]` - The aspectj compiler classpath.
By default resolved from `aspectjToolsDeps`.

* `def ajcOptions: T[Seq[String]]` - Additional options to be used by `ajc` in the `compile` target.

* `def aspectPath: T[Agg[PathRef]]` - Additional classes, JARs or ZIPs to be used as aspect path (`ajc -aspectpath`).
In most cases it is enough to use `aspectModuleDeps` and `aspectIvyDeps`.

* `def aspectModuleDeps: Seq[JavaModule]` - List of modules to be used as aspect path (`ajc -aspectpath`).

* `def aspectIvyDeps: T[Agg[Dep]]` - List of ivy dependencies to be used as aspect path (`ajc -aspectpath`).

* `def effectiveAspectPath: T[Seq[PathRef]]` - Effective aspect path (`ajc -inpath`).
In most cases, it is enough to use `aspectModuleDeps` and `aspectIvyDeps`.

* `def weavePath: T[Seq[PathRef]]`- List of directories with `.class` files to weave (into target directory).
Corresponds to `ajc -inpath` option.

* `def compile: T[CompilationResult]` - Compiles the source code with the ajc compiler.

* `def ajcHelp: Command[Unit]` - Shows the help of the AspectJ compiler (`ajc -help`).

== License

Apache License, version 2

== Supporters

Thanks to https://iba-cg.de/[iba Consulting Gesellschaft mbH & Co KG] for the initial development support.

== Changelog

No releases yet.